---
- name: Set certs for greengrass
  become: true
  copy:
    src: certs
    dest: /greengrass
    owner: root
    group: root
    mode: "0755"

- name: Set config for greengrass
  become: true
  copy:
    src: config
    dest: /greengrass
    owner: root
    group: root
    mode: "0755"